"""Add session_id, expires_at, metadata_json

Revision ID: ddb64cd061de
Revises: 0a39ab5d5a56
Create Date: 2026-06-19 22:29:31.873471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb64cd061de'
down_revision: Union[str, Sequence[str], None] = '0a39ab5d5a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matters', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('matters', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_matters_session_id'), 'matters', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matters_session_id'), table_name='matters')
    op.drop_column('matters', 'session_id')
    op.drop_column('matters', 'expires_at')
    op.drop_column('documents', 'metadata_json')
    # ### end Alembic commands ###
